trigger:
  branches:
    include:
      - develop

variables:
  - group: tpfinal-vars

stages:
  - stage: Build
    jobs:
      - job: BuildFront
        pool:
          name: Default
        steps:
          - template: templates/_build-front.yml